export type Metric={mean:number;sd:number;se:number;ci95:number[];n:number}; export type Aggregate={customers:number;dynamism:number;strategy:string;metrics:Record<string,Metric>}; export type ResultsData={aggregated:Aggregate[];paired_comparisons:any[];demo_scenarios:any[];note:string;config:{customers:number[];dynamism:number[];seeds:number[];strategies:string[]}};
export type ApiMode='waking'|'live'|'static'; export type ApiStatus={mode:ApiMode;baseUrl?:string};
export const labels:Record<string,string>={greedy_insertion:'A · Greedy insertion',insertion_2opt_star:'B · Insertion + 2-opt*',tabu_search:'C · Tabu search',adaptive_selector:'D · Adaptive selector'}; export const colors:Record<string,string>={greedy_insertion:'#B4FF39',insertion_2opt_star:'#39FF88',tabu_search:'#F2FFE9',adaptive_selector:'#73F7E5'};
const configured=(import.meta.env.VITE_API_URL||'').replace(/\/$/,''); let current:ApiStatus={mode:configured?'waking':'static',baseUrl:configured||undefined}; let checked=false;
async function timed(url:string,init?:RequestInit){const controller=new AbortController();const timer=window.setTimeout(()=>controller.abort(),8000);try{return await fetch(url,{...init,signal:controller.signal})}finally{window.clearTimeout(timer)}}
export async function checkApi():Promise<ApiStatus>{if(!configured){current={mode:'static'};return current}try{const response=await timed(`${configured}/api/v1/health`);current=response.ok?{mode:'live',baseUrl:configured}:{mode:'static',baseUrl:configured}}catch{current={mode:'static',baseUrl:configured}}return current}
export function apiStatus(){return current}
export function startHealthRetry(onChange:(status:ApiStatus)=>void){if(!configured||checked)return()=>{};checked=true;let attempts=0;const tick=async()=>{const next=await checkApi();onChange(next);attempts+=1;if(next.mode!=='live'&&attempts<6)window.setTimeout(tick,10000)};void tick();return()=>{attempts=6}}
export async function load():Promise<ResultsData>{const status=await checkApi();const url=status.mode==='live'?`${configured}/api/v1/results`:'/demo/results.json';const response=await timed(url);if(!response.ok)throw new Error('Results are unavailable');return response.json()}
export async function loadDemoScenarios():Promise<any[]>{const status=await checkApi();if(status.mode==='live'){const response=await timed(`${configured}/api/v1/demo-scenarios`);if(response.ok)return (await response.json()).demo_scenarios}return (await load()).demo_scenarios}
export async function loadDemoIndex():Promise<{id:number;dynamism:number}[]>{const response=await timed('/demo/index.json');if(!response.ok)throw new Error('Demo index is unavailable');return (await response.json()).scenarios}
export async function createScenario(payload:Record<string,unknown>){if(current.mode!=='live'||!configured)throw new Error('Requires the backend');const response=await timed(`${configured}/api/v1/scenarios`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});if(!response.ok)throw new Error('Scenario request failed');return response.json()}
export async function startSimulation(payload:Record<string,unknown>){if(current.mode!=='live'||!configured)throw new Error('Requires the backend');const response=await timed(`${configured}/api/v1/simulations`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});if(!response.ok)throw new Error('Simulation request failed');return response.json()}
export async function compareScenario(payload:Record<string,unknown>){if(current.mode!=='live'||!configured)throw new Error('Requires the backend');const response=await timed(`${configured}/api/v1/compare`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});if(!response.ok){const body=await response.json().catch(()=>({detail:'Comparison request failed'}));throw new Error(body.detail||'Comparison request failed')}return response.json()}
export async function loadTrace(runId:string){if(current.mode!=='live'||!configured)throw new Error('Requires the backend');const response=await timed(`${configured}/api/v1/simulations/${runId}/trace`);if(!response.ok)throw new Error('Trace request failed');return (await response.text()).split('\n').filter(Boolean).map(line=>JSON.parse(line))}
