import type { ReactNode } from 'react'; import { Link,useLocation } from 'react-router-dom';
type IconName='home'|'map'|'play'|'compare'|'chart'|'flask'|'book';
const paths:Record<IconName,string>={home:'M3 10.5 12 3l9 7.5v9a1.5 1.5 0 0 1-1.5 1.5h-15A1.5 1.5 0 0 1 3 19.5v-9Z M9 21v-6h6v6',map:'m3 6 6-3 6 3 6-3v15l-6 3-6-3-6 3V6Z M9 3v15 M15 6v15',play:'M8 5v14l11-7L8 5Z',compare:'M4 5h16M4 12h11M4 19h16',chart:'M4 19V5m0 14h16M8 16v-4m4 4V8m4 8V5',flask:'M9 3h6m-5 0v6l-5 9a2 2 0 0 0 1.7 3h10.6a2 2 0 0 0 1.7-3l-5-9V3',book:'M4 5.5A2.5 2.5 0 0 1 6.5 3H20v16H6.5A2.5 2.5 0 0 0 4 21.5v-16Z M4 19h16'};
function Icon({name}:{name:IconName}){return <svg className="nav-icon" viewBox="0 0 24 24" aria-hidden="true"><path d={paths[name]}/></svg>}
const links:{path:string;label:string;icon:IconName}[]=[{path:'/overview',label:'Overview',icon:'home'},{path:'/lab',label:'Scenario Lab',icon:'map'},{path:'/replay',label:'Replay',icon:'play'},{path:'/compare',label:'Compare',icon:'compare'},{path:'/results',label:'Results',icon:'chart'},{path:'/experiments',label:'Experiments',icon:'flask'},{path:'/methodology',label:'Methodology',icon:'book'}];
const titles:Record<string,string>={'/overview':'Overview','/lab':'Scenario Lab','/replay':'Simulation Replay','/compare':'Compare strategies','/results':'Experiment results','/experiments':'Experiments','/methodology':'Methodology'};
export function Layout({children}:{children:ReactNode}){const {pathname}=useLocation();return <div className="app-shell"><aside className="sidebar"><div className="brand"><div className="brand-mark">AR</div><div><div className="eyebrow">Adaptive Route Repair</div><div className="brand-name">DVRP Research Lab</div></div></div><nav>{links.map(link=><Link className={`nav-link ${pathname===link.path?'active':''}`} key={link.path} to={link.path}><Icon name={link.icon}/>{link.label}</Link>)}</nav></aside><div className="main-area"><header className="topbar"><div className="topbar-title">{titles[pathname]||'Page not found'}</div><span className="badge">Precomputed from real engine runs (n=5 seeds)</span></header><main className="content">{children}</main></div></div>}
export function PageHead({title,children}:{title:string;children?:ReactNode}){return <div className="page-head"><div><h1 className="page-title">{title}</h1>{children}</div></div>}
export function Loading(){return <div className="grid grid-3">{[1,2,3].map(i=><div className="panel" key={i}><div className="skeleton" style={{height:14,width:'42%',marginBottom:18}}/><div className="skeleton" style={{height:36,width:'70%'}}/></div>)}</div>}
